"""Emit HealthTasks_<version>.ttl from the enriched JSON plus context IRI dictionary."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
ONTOLOGIES_DIR = REPO / "src" / "assets" / "ontologies"
DEFAULT_VERSION = "2026.05.19"

HA_ACT_PREFIX = "https://w3id.org/calendar-bench/human-activities/activity/"

DIFFICULTY_COMMENT = {
    "Level1": "Difficulty 1 (almost effortless)",
    "Level2": "Difficulty 2 (light)",
    "Level3": "Difficulty 3 (moderate)",
    "Level4": "Difficulty 4 (hardest in this benchmark)",
}

DOMAIN_TO_LABEL = {
    "Nutrition": "Nutrition",
    "MentalWellbeing": "Mental Wellbeing",
    "PhysicalActivity": "Physical Activity",
}


def _camel_split(name: str) -> str:
    """Split a CamelCase identifier into space-separated words."""
    return re.sub(r"(?<!^)(?=[A-Z])", " ", name)


def _ttl_escape(s: str) -> str:
    """Escape backslashes, quotes, and newlines for a TTL string literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def _activity_curie(iri: str) -> str:
    """Render a human-activities IRI as the `ha-act:` CURIE used by 05.18; otherwise full IRI."""
    if iri.startswith(HA_ACT_PREFIX):
        return "ha-act:" + iri[len(HA_ACT_PREFIX) :]
    return f"<{iri}>"


def load_context_iris(path: Path) -> dict[str, dict[str, str]]:
    """Load context_iris.json and return {category: {slug: iri}}."""
    data = json.loads(path.read_text(encoding="utf-8"))
    out: dict[str, dict[str, str]] = {}
    for cat, members in data["context"].items():
        out[cat] = {slug: entry["iri"] for slug, entry in members.items()}
    return out


def emit_prelude(version: str) -> str:
    """Return the @prefix declarations, the ontology header, and property declarations."""
    return (
        "## ----------------------------------------------------------------------\n"
        "## Calendar-Bench HealthTasks knowledge graph.\n"
        f"## Generated by src/scripts/generate_healthtasks_ttl.py (version {version}).\n"
        "## ----------------------------------------------------------------------\n"
        "\n"
        "@prefix hb:      <https://w3id.org/calendar-bench/health/> .\n"
        "@prefix hb-tk:   <https://w3id.org/calendar-bench/health/task/> .\n"
        "@prefix ha:      <https://w3id.org/calendar-bench/human-activities/> .\n"
        "@prefix ha-act:  <https://w3id.org/calendar-bench/human-activities/activity/> .\n"
        "@prefix owl:     <http://www.w3.org/2002/07/owl#> .\n"
        "@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n"
        "@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .\n"
        "@prefix xsd:     <http://www.w3.org/2001/XMLSchema#> .\n"
        "@prefix dcterms: <http://purl.org/dc/terms/> .\n"
        "\n"
        "\n"
        "<https://w3id.org/calendar-bench/health/> a owl:Ontology ;\n"
        '    dcterms:title       "Calendar-Bench Health Tasks ontology"@en ;\n'
        '    dcterms:description "Health task benchmark organised as Domain, Challenge, Difficulty, Task. '
        "Each task carries title, description, isConcurrent, isDividable, estimatedDurationMinutes, "
        "matchedActivity (Compendium of Physical Activities bridge) and contextLink edges into the "
        'curated context IRI dictionary (mood, energy, location, weather, behaviour-theory categories)."@en ;\n'
        f'    owl:versionInfo     "{version}" .\n'
        "\n"
        "\n"
        "## ----------------------------------------------------------------------\n"
        "## Datatype and object properties\n"
        "## ----------------------------------------------------------------------\n"
        "\n"
        "hb:isConcurrent a owl:DatatypeProperty , owl:FunctionalProperty ;\n"
        "    rdfs:domain hb:HealthTask ;\n"
        "    rdfs:range  xsd:boolean ;\n"
        '    rdfs:label  "is concurrent"@en ;\n'
        '    rdfs:comment "True when the task is light enough to attach to another focused calendar block."@en .\n'
        "\n"
        "hb:isDividable a owl:DatatypeProperty , owl:FunctionalProperty ;\n"
        "    rdfs:domain hb:HealthTask ;\n"
        "    rdfs:range  xsd:boolean ;\n"
        '    rdfs:label  "is dividable"@en ;\n'
        '    rdfs:comment "True when the task can be split across multiple time slots in the day."@en .\n'
        "\n"
        "hb:estimatedDurationMinutes a owl:DatatypeProperty , owl:FunctionalProperty ;\n"
        "    rdfs:domain hb:HealthTask ;\n"
        "    rdfs:range  xsd:integer ;\n"
        '    rdfs:label  "estimated duration in minutes"@en ;\n'
        '    rdfs:comment "Realistic length in minutes per single instance of the task."@en .\n'
        "\n"
        "hb:matchedActivity a owl:ObjectProperty ;\n"
        "    rdfs:domain hb:HealthTask ;\n"
        "    rdfs:range  ha:HumanActivity ;\n"
        '    rdfs:label  "matched activity"@en ;\n'
        '    rdfs:comment "Bridge from a HealthTask to the most representative Compendium of Physical Activities instance."@en .\n'
        "\n"
        "hb:contextLink a owl:ObjectProperty ;\n"
        "    rdfs:domain hb:HealthTask ;\n"
        '    rdfs:label  "context link"@en ;\n'
        '    rdfs:comment "Bridge from a HealthTask to a context IRI curated in context_iris.json '
        '(mood, energy, location, weather, social, stress, physiological and behaviour-theory categories)."@en .\n'
    )


def emit_taxonomy(data: dict) -> str:
    """Emit the sparse class hierarchy; only Level N classes that carry tasks are produced."""
    lines: list[str] = [
        "\n## ----------------------------------------------------------------------\n"
        "## Class hierarchy (T-Box)\n"
        "## ----------------------------------------------------------------------\n",
        "hb:HealthTask a owl:Class ;\n"
        '    rdfs:label   "Health Task"@en ;\n'
        '    rdfs:comment "Any small, schedulable health behaviour from the calendar-bench benchmark."@en .\n',
    ]

    for dom in sorted(data):
        lines.append(
            f"hb:{dom}Task a owl:Class ;\n"
            f"    rdfs:subClassOf hb:HealthTask ;\n"
            f'    rdfs:label "{DOMAIN_TO_LABEL[dom]}"@en .\n'
        )

    for dom in sorted(data):
        for cat in sorted(data[dom]):
            cat_label = _camel_split(cat)
            lines.append(
                f"hb:{dom}{cat}Task a owl:Class ;\n"
                f"    rdfs:subClassOf hb:{dom}Task ;\n"
                f'    rdfs:label "{DOMAIN_TO_LABEL[dom]} - {cat_label}"@en .\n'
            )

    for dom in sorted(data):
        for cat in sorted(data[dom]):
            for lvl in sorted(data[dom][cat]):
                tasks = data[dom][cat][lvl]
                if not tasks:
                    continue
                cat_label = _camel_split(cat)
                comment = DIFFICULTY_COMMENT[lvl]
                lines.append(
                    f"hb:{dom}{cat}{lvl} a owl:Class ;\n"
                    f"    rdfs:subClassOf hb:{dom}{cat}Task ;\n"
                    f'    rdfs:label "{DOMAIN_TO_LABEL[dom]} - {cat_label} - {lvl[:-1]} {lvl[-1]}"@en ;\n'
                    f'    rdfs:comment "{comment} within {DOMAIN_TO_LABEL[dom]} - {cat_label}."@en .\n'
                )
    return "\n".join(lines)


def emit_task(
    domain: str,
    cat: str,
    lvl: str,
    task_id: str,
    task: dict,
    iri_lookup: dict[str, dict[str, str]],
) -> str:
    """Emit one task individual with title, description, flags, matchedActivity and contextLink edges."""
    cls = f"hb:{domain}{cat}{lvl}"
    title = _ttl_escape(task["title"])
    desc = _ttl_escape(task["description"])
    duration = int(task["estimatedDuration"])
    is_conc = str(task["isConcurrent"]).lower()
    is_div = str(task["isDividable"]).lower()

    matched = task.get("matchedActivity") or []
    if isinstance(matched, str):
        matched = [matched]

    context_links = task.get("context_links") or {}
    target_iris: list[str] = []
    for c in sorted(context_links):
        members = iri_lookup.get(c)
        if members is None:
            raise ValueError(
                f"task {task_id!r}: context category {c!r} not present in context_iris.json"
            )
        for slug in context_links[c]:
            iri = members.get(slug)
            if iri is None:
                raise ValueError(
                    f"task {task_id!r}: context_links[{c!r}] slug {slug!r} not in context_iris.json[{c!r}]"
                )
            target_iris.append(iri)

    lines = [
        f"hb-tk:{task_id} a {cls} ;",
        f'    dcterms:title       "{title}" ;',
        f'    dcterms:description "{desc}" ;',
        f"    hb:estimatedDurationMinutes {duration} ;",
        f"    hb:isConcurrent     {is_conc} ;",
        f"    hb:isDividable      {is_div}",
    ]
    for iri in matched:
        lines[-1] += " ;"
        lines.append(f"    hb:matchedActivity {_activity_curie(iri)}")
    for iri in target_iris:
        lines[-1] += " ;"
        lines.append(f"    hb:contextLink     <{iri}>")
    lines[-1] += " ."
    return "\n".join(lines) + "\n"


def generate_ttl(
    json_path: Path,
    iris_path: Path,
    out_path: Path,
    version: str,
) -> int:
    """Generate the TTL file and return the number of task individuals emitted."""
    data = json.loads(json_path.read_text(encoding="utf-8"))
    iri_lookup = load_context_iris(iris_path)

    parts = [
        emit_prelude(version),
        emit_taxonomy(data),
        "\n## ----------------------------------------------------------------------\n"
        "## Task individuals (A-Box)\n"
        "## ----------------------------------------------------------------------\n",
    ]
    n = 0
    for dom in sorted(data):
        for cat in sorted(data[dom]):
            for lvl in sorted(data[dom][cat]):
                for tid in sorted(data[dom][cat][lvl]):
                    task = data[dom][cat][lvl][tid]
                    parts.append(emit_task(dom, cat, lvl, tid, task, iri_lookup))
                    n += 1

    out_path.write_text("\n".join(parts), encoding="utf-8")
    return n


def main(argv: list[str] | None = None) -> None:
    """Regenerate HealthTasks_<version>.ttl from the matching JSON and context_iris.json."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--version",
        default=DEFAULT_VERSION,
        help="HealthTasks dataset version (e.g. 2026.05.19)",
    )
    parser.add_argument(
        "--ontologies-dir",
        type=Path,
        default=ONTOLOGIES_DIR,
        help="Directory holding HealthTasks_<version>.json and context_iris.json",
    )
    args = parser.parse_args(argv)

    json_path = args.ontologies_dir / f"HealthTasks_{args.version}.json"
    iris_path = args.ontologies_dir / "context_iris.json"
    out_path = args.ontologies_dir / f"HealthTasks_{args.version}.ttl"

    if not json_path.exists():
        raise FileNotFoundError(json_path)
    if not iris_path.exists():
        raise FileNotFoundError(iris_path)

    n = generate_ttl(json_path, iris_path, out_path, args.version)
    try:
        display = out_path.relative_to(REPO)
    except ValueError:
        display = out_path
    print(f"Wrote {display} with {n} task individuals.")


if __name__ == "__main__":
    main()
